"""empty message

Revision ID: 3ab810fa9016
Revises: c7ad9bde0b82
Create Date: 2025-05-20 11:58:21.174344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab810fa9016'
down_revision: Union[str, None] = 'c7ad9bde0b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('user_profiles', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('user_profiles', 'heshed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('heshed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'hashed_password')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
